project:
  type: website
  output-dir: docs

website:
  title: "Noah Hutabarat"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - hobbies.qmd

format:
  html:
    theme: vapor



